### ISSUE TITLE
Development URL from config.json not working

### ISSUE THREAD

**Issue by kiogo** [htmlburger/wpemerge-theme#68] opened 2021-02-10 21:13 UTC
## Version

_Please add the exact versions used for each of the following:_

  - WP Emerge Starter Theme: 0.16.2
  - WP Emerge (if not the default):
  - WordPress:
  - PHP:

## Expected behavior

_Please describe the expected behavior here._

Expect running yarn start to use the development url specified in config.json

## Actual behavior

_Please describe the actual, unexpected behavior here._

No matter what is entered, localhost:3000 is used for CSS/JS assets.

## Steps to reproduce (in case of a bug)

  1.
  1.
  1.

## Comments

_Please add any other comments here._

Running local dev under Laravel Valet and need to specify the local URL for outputting CSS/JS paths.

**Comment by atanas-dev** [comment] 2021-02-10 22:14
Hi @kiogo ,

Could you please share the `"development"` part of your config.json file?

**Comment by kiogo** [comment] 2021-02-10 23:19
```},
"development": {
    "url": "http://clientdev.test/",
    "hotUrl": "http://clientdev.test/",
    "port": 3000
  },

**Comment by atanas-dev** [comment] 2021-02-10 23:39
Thank you for the report - I'll look into it.
In the meantime, you can replace the values in the development Webpack config directly as a workaround:
https://github.com/htmlburger/wpemerge-theme/blob/master/resources/build/webpack.development.js#L228:L230

**Comment by atanas-dev** [comment] 2021-03-14 18:38
Ultimately I was unable to reproduce the issue. That being said, the current "url" config is kind of misleading as it is not used *right now*. Here's how URLs are being used in different build modes:
- `yarn start`: Since files are committed to disk, assets are loaded using the `'app_core' => 'url'` config.php option which defaults to `get_template_directory_uri()`.
- `yarn hot`: No files are committed to disk, uses `hotUrl` from `config.json` or defaults to `localhost`.
- `yarn build`: Since files are committed to disk, behaves the same way `yarn start` does by using the base URL from `config.php`.

**Closed as completed by atanas-dev** 2021-03-14 18:38 UTC
Labels: bug

**Comment by jorostoyanov** [comment] 2021-04-29 06:11
Same issue appeared here.

Solved by declaring `define( 'SCRIPT_DEBUG', true );` in `wp-config.php`

Otherwise, `WPEmergeAppCore\Assets\Assets::getBundleUrl()` is trying to load the minified version of the asset file.

Hope that helps :)

**Comment by atanas-dev** [comment] 2021-05-15 19:02
@jorostoyanov 👋
Could you please confirm you can reproduce the issue with `htmlburger/wpemerge-app-core`:0.16.1?

There was a hotfix awhile back that addresses some issues with asset loading:
https://github.com/htmlburger/wpemerge-app-core/releases/tag/0.16.1

Also:
https://github.com/htmlburger/wpemerge-theme/releases/tag/0.16.2
